config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 15 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You need log in to perform this action"
      redirect_to login_path
    end
  end

  def logged_in_redirect
    if logged_in?
        flash[:error] = "You already logged in"
        redirect_to root_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @messages = Message.all
    @users = User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    @message = Message.new(params.require(:message).permit(:body))
    @message.user = current_user
    ActionCable.server.broadcast 'chatroom_channel', { mod_message: message_render(@message) } if @message.save
  end

  private
  
  def message_render(message)
    render(partial: "message", locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]
  def new; end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:error] = 'Wrong username or password, please try again!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_redirect
  def new; end

  def create
    @user = User.new(params.require(:user).permit(:username, :password))
    if @user.save
      flash[:success] = 'Sign up successfully!'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
    <i class="circular orange coffee icon"></i>
    Say something
</h2>
<div class="ui grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div class="ui feed" id="message-container">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
                <%= form_with(scope: :message, url: message_path, local: false, html: {class: "ui form"}) do |form|%>
                <div class="ui fluid input">
                    <%= form.text_field :body, autofocus: true, id: "message-input" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <div class="four wide column">
        <div class="ui fluid raised card online-user-box">
            <div class="content" id="user-list">
                <div class="ui inverted vertical menu" id="user-container">
                    <p class="active item">
                        Online user
                    </p>
                    <% @users.each do |user| %>
                    <p class="item" id="user-item" data-user-id="<%= user.id %>">
                        <%= user.username%>
                        <% if user.online %>
                        <a class="ui mini green empty circular label" id="online-flag"></a>
                        <% end %>
                    </p>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="ui inverted menu">
    <div class="ui container">
        <%= link_to "Chatroom", root_path, class: "item"%>
        <div class="right menu">
            <div class="ui dropdown item">
                Account <i class="dropdown icon"></i>
                <div class="menu">
                    <% if !logged_in? %>
                    <%= link_to "Log in", login_path, class: "item" %>
                    <%= link_to "Sign up", signup_path, class: "item" %>
                    <% else %>
                    <%= link_to "Log out", logout_path, class: "item", method: :delete %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_notify.html.erb
<% flash.each do |type, message| %>
<div class="ui <%= type %> message transition">
    <i class="close icon"></i>
    <% if message.class == Array %>
    <ul class="list">
        <% message.each do |msg|%>
        <li class="header"><%= msg %></li>
        <% end %>
    </ul>
    <% else %>
    <p class="header"><%= message %></p>
    <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render "layouts/navbar" %>
    <div class="ui container">
    <%= render "layouts/notify" %>
        <%= yield %>
    </div>
</body>

</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h2 class="ui center aligned header">Welcome to Message Me</h2>
<h3 class="ui center aligned icon header">
    <i class="circular orange power off icon"></i>
    Signup
</h3>
<div class="ui placeholder segment">
    <div class="ui column very relaxed stackable grid">
        <div class="column">
            <%= form_with(scope: :user, url: signup_path, html: {class: "ui form"}) do |form| %>
            <div class="field">
                <%= form.label :username, "Username" %>
                <div class="ui left icon input">
                    <%= form.text_field :username, placeholder: "Enter your username" %>
                    <i class="user icon"></i>
                </div>
            </div>
            <div class="field">
                <%= form.label :password, "Password" %>
                <div class="ui left icon input">
                    <%= form.text_field :password, placeholder: "Enter your password", type: 'password' %>
                    <i class="lock icon"></i>
                </div>
            </div>
            <%= form.submit "Signup", class: "ui orange submit button" %>
            <% end %>
        </div>
    </div>
</div>